server:
  port: 8081
spring:
  output:
    ansi:
      enabled: always
  datasource:
    username: root
    password: Mysql@2023
    url: jdbc:mysql://localhost:3306/flight_reservation_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: FLIGHTSERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka


