server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: thomas.webeqt@gmail.com
    password: ulumouifaftzlhef
#    properties:
#      mail:
#      smtp:
#      auth: true
#      starttls:
#      enable: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    username: root
    password: Mysql@2023
    url: jdbc:mysql://localhost:3306/flight_reservation_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: FLIGHTBOOKINGSERVICE


