spring:
  datasource:
    username: root
    password: Mysql@2023
    url: jdbc:mysql://localhost:3306/flight_reservation_db
  output:
    ansi:
      enabled: always
  security:
    user:
      name: mahima
      password: securepswd
  application:
    name: USERSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka